// Chapter 16: a Blueprint Function Library — static C++ functions callable from any
// Blueprint graph. Perfect for trying Unreal types without setting up a level.
#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "CLPrimerLibrary.generated.h" // must be the LAST include: generated by UnrealHeaderTool

// UENUM exposes an enum to reflection (Blueprints, editor dropdowns, serialization).
UENUM(BlueprintType)
enum class ECLRarity : uint8
{
	Common    UMETA(DisplayName = "Common"),
	Rare      UMETA(DisplayName = "Rare"),
	Legendary UMETA(DisplayName = "Legendary")
};

// USTRUCT: a reflected value type (no GC, copied by value, prefix F).
USTRUCT(BlueprintType)
struct FCLItem
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Item")
	FName Id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Item")
	FText DisplayName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Item", meta = (ClampMin = "0"))
	int32 Price = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Item")
	ECLRarity Rarity = ECLRarity::Common;
};

UCLASS()
class CLEARNGAME_API UCLPrimerLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	// Logs a tour of FString / FName / FText / TArray / TMap to the Output Log.
	UFUNCTION(BlueprintCallable, Category = "CLearn|Primer")
	static void RunPrimerTour();

	// BlueprintPure: no exec pins, no side effects.
	UFUNCTION(BlueprintPure, Category = "CLearn|Primer")
	static int32 TotalPrice(const TArray<FCLItem>& Items);

	UFUNCTION(BlueprintPure, Category = "CLearn|Primer")
	static TArray<FCLItem> FilterByRarity(const TArray<FCLItem>& Items, ECLRarity Rarity);

	// Returns false (instead of throwing — UE has no exceptions) when not found.
	UFUNCTION(BlueprintCallable, Category = "CLearn|Primer")
	static bool FindItemById(const TArray<FCLItem>& Items, FName Id, FCLItem& OutItem);
};
